#!/usr/bin/env php
<?php

include __DIR__ . "/vendor/autoload.php";

use App\CreateCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new CreateCommand());

$application->run();
